### ISSUE TITLE
Incorrect label position when 3D text is present

### ISSUE THREAD

**Issue by organicpencil** [DCubix/Compz#1]
When a 3D text object with default font is present, the first label does not render in the correct position.
To replicate:  Add a text object to test.blend.  The play button text will be too high.

**Comment by DCubix** [comment]
I temporarily fixed this. With an ugly hack (i'm sorry). This is most likely a BGE bug rather than a bug in the module...
Tell me if it works!

**Comment by organicpencil** [comment]
Works good!  Does kinda seem like an engine bug.  Thanks for the workaround!
